spring.application.name=KanbanBoardServer

# Подключение к БД
spring.datasource.url=jdbc:postgresql://localhost/KanbanBoardDB
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Параметры Hibernate и JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Параметры Swagger
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.enabled=true

# Конфигурация файлов
upload.path=C:/Users/PC/Documents/kbn
spring.servlet.multipart.max-file-size=10MB

# Ключ для подписи JWT
token.signing.key=${TOKEN_SIGNING_KEY}